In [1]:
import numpy as np

In [2]:
#Exercise 1
integer_array = np.arange(100,200,10)
integer_array.reshape(5,2)


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [3]:
#Exercise 2
sample_array = np.array([[11,22,33],[44,55,66],[77,88,99]])
sample_array[0:,2]

array([33, 66, 99])

In [4]:
#Exercise 3
array_1 = np.array([[5,6,9],[21,18,27]])
array_2 = np.array([[15,33,24],[4,7,1]])
sum_array = array_1 + array_2
print("The sum of array_1 and array_2 is:{}".format(sum_array))
sqrt_array = np.square(sum_array)
print("The square root of the sum_array is: {}".format(sqrt_array))


The sum of array_1 and array_2 is:[[20 39 33]
 [25 25 28]]
The square root of the sum_array is: [[ 400 1521 1089]
 [ 625  625  784]]
